### ISSUE TITLE
Something wrong with GitHub Pages

### ISSUE THREAD

**Issue by tokunagamuy** [piazzai/hacked-jekyll#5]
Good evening. I am an economist from Japan. While attempting to create a personal website for my research, I came across your excellent template. However, after forking it as my repository and deploying it live on GitHub Pages, the design for JSON seems to be missing, as shown in the image below.

![スクリーンショット 2024-01-03 224956](https://github.com/piazzai/hacked-jekyll/assets/153994037/301fbe3f-b86f-4c16-8bb4-cf9296a643ba)

As a complete novice in GitHub and CSS, I'm struggling to pinpoint the exact bug. Could it be a mistake in my procedures? I haven't altered the file order or paths. I apologize for reaching out amidst your busy schedule, but could you please assist me in rectifying my site's design?

**Comment by piazzai** [comment]
Hello! Thank you for your interest in the theme. I'm glad to help.

If my reconstruction of what you have been doing is correct, the repository you are trying to publish is `tokunagamuy/hacked-jekyll`. GitHub pages will attempt to publish this as a project website and not as a personal website. For personal websites, the repository name must necessarily be `username.github.io`.

This theme is intended for personal websites. The misbehavior you are experiencing is due to the fact that you are trying to publish it as a project website. (In particular, the problem occurs because CSS stylesheets are not found at the location where they are expected.) To solve the problem, just rename the repository to `tokunagamuy.github.io`. Everything should then fix itself.

If there is any particular reason why you want to use the theme for a project website, then you have to open the file `_includes/head.html` and edit lines 15-17:

```
<link rel="stylesheet" href="/assets/css/normalize.min.css" />
<link rel="stylesheet" href="/assets/css/open-color.min.css" />
<link rel="stylesheet" href="/assets/css/styles.min.css" />
```

~~I think removing the starting `/` from the `href` field might be sufficient, but I am not sure. Let me know, in case, and I can look at the issue more carefully.~~

EDIT: If you edit the lines above as follows, Jekyll should be able to find the stylesheets.

```
<link rel="stylesheet" href="{{ '/assets/css/normalize.min.css' | relative_url }}" />
<link rel="stylesheet" href="{{ '/assets/css/open-color.min.css' | relative_url }}" />
<link rel="stylesheet" href="{{ '/assets/css/styles.min.css' | relative_url }}" />
```

I didn't test this, but I think it will work. Let me know, in case.

**Comment by tokunagamuy** [comment]
Grazie mille!! I could solve all of my problems thanks to your insights. 
By the way, I tried both two of codes that you suggested, but both successfully worked.
Best regards 💯

**Comment by piazzai** [comment]
Happy it worked! The `relative_url` fix should probably be implemented in the theme. I'll keep it in mind for the next release.
